-- ============================================================
-- RBAC 基础框架数据库表结构
-- 适用：PostgreSQL 12+
-- 包含：users / roles / permissions / user_roles / role_permissions
-- ============================================================

-- 开启事务，确保原子性
BEGIN;

-- ------------------------------------------------------------
-- 1. 用户表
-- ------------------------------------------------------------
DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64)  NOT NULL,
    email         VARCHAR(128) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    avatar        VARCHAR(512)          DEFAULT NULL,
    status        SMALLINT     NOT NULL DEFAULT 1,
    last_login_at TIMESTAMP             DEFAULT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 唯一索引
CREATE UNIQUE INDEX uk_username ON users (username);
CREATE UNIQUE INDEX uk_email ON users (email);

-- 自动更新时间触发器函数（可选，模拟 MySQL 的 ON UPDATE）
CREATE OR REPLACE FUNCTION update_updated_at_column()
    RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE
    ON users
    FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

COMMENT ON TABLE users IS '用户表';
COMMENT ON COLUMN users.id IS '用户 ID';
COMMENT ON COLUMN users.username IS '用户名（唯一）';
COMMENT ON COLUMN users.email IS '邮箱（唯一）';
COMMENT ON COLUMN users.password_hash IS 'bcrypt 加密密码';
COMMENT ON COLUMN users.avatar IS '头像 URL';
COMMENT ON COLUMN users.status IS '状态：1=正常 0=禁用';
COMMENT ON COLUMN users.last_login_at IS '最后登录时间';


-- ------------------------------------------------------------
-- 2. 角色表
-- ------------------------------------------------------------
DROP TABLE IF EXISTS roles CASCADE;
CREATE TABLE roles
(
    id          SERIAL PRIMARY KEY, -- 或者使用 BIGINT GENERATED...
    name        VARCHAR(64) NOT NULL,
    label       VARCHAR(64) NOT NULL,
    description VARCHAR(255)         DEFAULT NULL,
    scope       SMALLINT    NOT NULL DEFAULT 2,
    status      SMALLINT    NOT NULL DEFAULT 1,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_role_name ON roles (name);

COMMENT ON TABLE roles IS '角色表';
COMMENT ON COLUMN roles.id IS '角色 ID';
COMMENT ON COLUMN roles.name IS '角色标识，如 super_admin / admin / user';
COMMENT ON COLUMN roles.label IS '角色展示名称';
COMMENT ON COLUMN roles.description IS '角色描述';
COMMENT ON COLUMN roles.scope IS '作用域：1=后台 2=前台';
COMMENT ON COLUMN roles.status IS '状态：1=启用 0=禁用';


-- ------------------------------------------------------------
-- 3. 权限表
-- ------------------------------------------------------------
DROP TABLE IF EXISTS permissions CASCADE;
CREATE TABLE permissions
(
    id         SERIAL PRIMARY KEY,
    name       VARCHAR(128) NOT NULL,
    label      VARCHAR(64)  NOT NULL,
    module     VARCHAR(64)  NOT NULL,
    status     SMALLINT     NOT NULL DEFAULT 1,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_perm_name ON permissions (name);
CREATE INDEX idx_module ON permissions (module);

COMMENT ON TABLE permissions IS '权限表';
COMMENT ON COLUMN permissions.id IS '权限 ID';
COMMENT ON COLUMN permissions.name IS '权限标识，格式 module:action，如 user:delete';
COMMENT ON COLUMN permissions.label IS '权限展示名称';
COMMENT ON COLUMN permissions.module IS '所属模块，如 user / article / order';


-- ------------------------------------------------------------
-- 4. 用户角色关联表
-- ------------------------------------------------------------
DROP TABLE IF EXISTS user_roles CASCADE;
CREATE TABLE user_roles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT    NOT NULL,
    role_id    INT       NOT NULL,
    granted_by BIGINT             DEFAULT NULL,
    granted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP          DEFAULT NULL,
    CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uk_user_role ON user_roles (user_id, role_id);
CREATE INDEX idx_role_id ON user_roles (role_id);

COMMENT ON TABLE user_roles IS '用户角色关联表';
COMMENT ON COLUMN user_roles.granted_by IS '授权操作人 user_id';
COMMENT ON COLUMN user_roles.expires_at IS '过期时间，NULL 表示永久有效';


-- ------------------------------------------------------------
-- 5. 角色权限关联表
-- ------------------------------------------------------------
DROP TABLE IF EXISTS role_permissions CASCADE;
CREATE TABLE role_permissions
(
    id            SERIAL PRIMARY KEY,
    role_id       INT NOT NULL,
    permission_id INT NOT NULL,
    CONSTRAINT fk_rp_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_rp_permission FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uk_role_perm ON role_permissions (role_id, permission_id);
CREATE INDEX idx_permission_id ON role_permissions (permission_id);

COMMENT ON TABLE role_permissions IS '角色权限关联表';

COMMIT;

-- ============================================================
-- 初始化数据
-- ============================================================

-- 角色
INSERT INTO roles (name, label, description, scope)
VALUES ('super_admin', '超级管理员', '拥有所有权限，代码层直接放行', 1),
       ('admin', '后台管理员', '可管理内容与普通用户', 1),
       ('user', '普通用户', '前台注册用户，拥有基础操作权限', 2);

-- 权限（module:action 格式）
INSERT INTO permissions (name, label, module)
VALUES ('user:list', '用户列表', 'user'),
       ('user:create', '创建用户', 'user'),
       ('user:update', '更新用户', 'user'),
       ('user:delete', '删除用户', 'user'),
       ('user:view', '查看用户', 'user'),
       ('user:assign-role', '分配角色', 'user'),
       ('role:list', '角色列表', 'role'),
       ('role:create', '创建角色', 'role'),
       ('role:update', '更新角色', 'role'),
       ('role:delete', '删除角色', 'role'),
       ('role:view', '查看角色', 'role'),
       ('role:assign-perm', '分配权限', 'role'),
       ('perm:list', '权限列表', 'perm'),
       ('perm:create', '创建权限', 'perm'),
       ('perm:update', '更新权限', 'perm'),
       ('perm:delete', '删除权限', 'perm'),
       ('perm:view', '查看权限', 'perm'),
       ('agent:chat', 'AI对话', 'agent'),
       ('agent:embedding', '添加向量', 'agent');

-- super_admin 角色权限（所有权限）
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r,
     permissions p
WHERE r.name = 'super_admin'
  AND p.name IN (select name from permissions);

-- admin 角色权限（用户管理 + 角色管理 + 权限管理 + AI对话）
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r,
     permissions p
WHERE r.name = 'admin'
  AND p.name IN (
                 'user:list', 'user:create', 'user:update', 'user:delete', 'user:view', 'user:assign-role',
                 'role:list', 'role:create', 'role:update', 'role:delete', 'role:view', 'role:assign-perm',
                 'perm:list', 'perm:create', 'perm:update', 'perm:delete', 'perm:view',
                 'agent:chat', 'agent:embedding'
    );

-- user 角色权限
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r,
     permissions p
WHERE r.name = 'user'
  AND p.name IN ('agent:chat','agent:embedding');

-- 插入超级管理员用户
INSERT INTO users (username, email, password_hash, avatar, status, created_at, updated_at)
VALUES ('admin', 'seehold@gmail.com', '$2a$10$6Z0lvw13OubWRwN/SBYyauiiT0.MMLaTwe.mxcRyeIlb3dq.bn24W', NULL,
        1, NOW(), NOW());
-- 设置权限
INSERT INTO user_roles (user_id, role_id, granted_by, granted_at, expires_at)
SELECT u.id, r.id, u.id, NOW(), NULL
FROM users u,
     roles r
WHERE u.username = 'admin'
  AND r.name = 'super_admin';


-- ============================================================
-- 常用查询 (PostgreSQL 版本)
-- ============================================================

-- 1. 查询某用户的所有角色
-- SELECT r.name, r.label
-- FROM user_roles ur
-- JOIN roles r ON r.id = ur.role_id AND r.status = 1
-- WHERE ur.user_id = 1
--   AND (ur.expires_at IS NULL OR ur.expires_at > NOW());

-- 2. 查询某用户的所有权限
-- SELECT DISTINCT p.name
-- FROM user_roles ur
-- JOIN roles r            ON r.id = ur.role_id         AND r.status = 1
-- JOIN role_permissions rp ON rp.role_id = ur.role_id
-- JOIN permissions p      ON p.id = rp.permission_id   AND p.status = 1
-- WHERE ur.user_id = 1
--   AND (ur.expires_at IS NULL OR ur.expires_at > NOW());

-- 3. 判断是否为超级管理员
-- SELECT COUNT(1)
-- FROM user_roles ur
-- JOIN roles r ON r.id = ur.role_id
-- WHERE ur.user_id = 1 AND r.name = 'super_admin'
--   AND (ur.expires_at IS NULL OR ur.expires_at > NOW());