# 将本文件复制为 application-local.yaml，并根据个人环境修改
# 由于 .gitignore 排除了实际文件
# 每个人的账号密码只保存在本地
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/base_framework?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
  ai:
    openai:
      api-key: your_key
      base-url: your_url
      chat:
        options:
          model: your_model
          temperature: 0.7
      embedding:
        options:
          model: your_model
    vectorstore:
      pgvector:
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 1536
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch